### ISSUE TITLE
Decide which framework to use

### ISSUE THREAD

**Issue by tauil** [wpolicarpo/got-board#1]
- [Angular](https://angularjs.org/) v1.x
- [Angular](https://angularjs.org/) v2.x
- [Backbone](http://backbonejs.org/) v1.x
- [Ember](http://emberjs.com/) v1.x
- [React](https://facebook.github.io/react/) v0.x + [Flux](https://github.com/facebook/flux)
- jQuery + polling :trollface: 

What else?

**Comment by vagnerzampieri** [comment]
Backbone

**Comment by tauil** [comment]
Yesterday me and @wpolicarpo talked a lot about which framework to use and we voted to Backbone because it's the most demanded nowadays, has as much pluging and strong community as angular and Angular has the update issue.

Backbone ++

**Comment by rodrigotassinari** [comment]
do you guys know [Discourse](http://www.discourse.org/)? it's an open-source forum application, built by the same guys who created [StackOverflow](https://stackoverflow.com/). the [source code](https://github.com/discourse/discourse) is on GitHub.

it's built as a Ruby on Rails backend with an Ember.js front-end, and it is extremely well written, and a good source of inspiration and good practice (both on the Rails/Ruby side and on the front-end side). the app has some **amazing** front-end experience, very impressive really. [give it a try](http://try.discourse.org/).

i would take a close look at it before discarding Ember.

**Comment by rodrigotassinari** [comment]
another example of ruby backend (a rails/grape api) + ember frontend: http://www.askr.me/ruby

here's the [ruby backend code](https://github.com/teamrarebit/askr-api) and here's the [ember front-end](https://github.com/teamrarebit/askr-ui) code.

**Comment by rodrigotassinari** [comment]
another example: https://www.wordset.org/

ruby (rails/grape) backend ([code](https://github.com/wordset/wordset-api)) + ember front-end ([code](https://github.com/wordset/wordset-ui))

**Comment by rodrigotassinari** [comment]
good book on backbone + rails: https://gumroad.com/l/backbone-js-on-rails/

**Comment by wpolicarpo** [comment]
We've decided by Ember. So, I'm closing this issue.
